server:
  port: 8080

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: currency_exchange
      username: rootuser
      password: rootpass
      authentication-database: admin
  cache:
    caffeine:
      spec: maximumSize=${cache.cache-max-size},expireAfterWrite=${cache.expiration.hours}h

nbp-api:
  base-url: https://api.nbp.pl
  exchange-rate-path-usd: /api/exchangerates/rates/A/USD/?format=json

cache:
  cache-init-capacity: 5
  cache-max-size: 100
  nbp:
    update-window:
      start-hour: 11
      start-minute: 45
      end-hour: 12
      end-minute: 15
      clear-cron: "0 45-59,0-15 11-12 * * MON-FRI"
  scheduling:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: caches, health, env, mappings, metrics, beans
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.cache: TRACE