server:
  port: 8080

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: currency_exchange
      username: rootuser
      password: rootpass
      authentication-database: admin
  cache:
    caffeine:
      spec: maximumSize=${cache.cache-max-size},expireAfterWrite=${cache.expiration.hours}h

nbp-api:
  base-url: https://api.nbp.pl
  exchange-rate-path-usd: /api/exchangerates/rates/A/USD/?format=json

cache:
  cache-init-capacity: 5
  cache-max-size: 100
  expiration:
    hours: 12

management:
  endpoints:
    web:
      exposure:
        include: caches, health, env, mappings, metrics, beans
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.cache: TRACE